extends:
  - plugin:jest/recommended
  - plugin:vue/essential
  - eslint:recommended

rules:
  indent:
    - error
    - 2
    - MemberExpression: off
  no-undef: error
  no-unused-vars: off
  operator-linebreak:
    - error
    - before
